### ISSUE TITLE
[BUG] "No data available for steady state settings", "No data for Channel 'FX'"

### ISSUE THREAD

**Issue by Gianluca2** [teasit/magic-formula-tyre-tool#3] opened 2023-06-09 21:20 UTC
**Description**
When I upload a Matlab file from TTC Round 8, No data channel is created for FX and No data available for steady state settings and I can't run the program. I'm not sure if I'm doing something wrong but I looked at everywhere all the resources but can't find the solution. I've seen the error with steady state settings be answer but I believe this issue is different. I get no FNOMIN when uploading the files.

Also in the tutorials it shows a parser for both cornering and breaking, for my program it only has one parser with the name ' FSAETTC_SI_ISO_Mat'

When I open the program, this error shows up:
    Error using matlab.ui.control.internal.model.AbstractNumericComponent/set.Value
    'Value' cannot be [] when 'AllowEmpty' is 'off'.
 
Unable to execute 'update' method.

**Reproduce**
1. Go to TTC round 8
2. Upload from RawData_Cornering_Matlab_SI_10inch_Round8 (Run data doesn't work either)
3. Any file number
4. Upload file
5. See error

**Version of MATLAB**
 - Matlab R2023a - Windows

**Comment by teasit** [comment] 2023-06-09 23:06
Hey Gianluca,

Have you tried using the example data provided with the repository? I suspect this might be a 2023 issue. I have only verified functionality withup to 2022b.

The fact that you can only see one parser is die to me "merging" the two. Many users were using the wrong parser often, so I tried to make it a bit more straight-forward.

Greetings Tom

**Comment by Gianluca2** [comment] 2023-06-10 09:42
Hello Tom, I tried running the program in 2022b, a similar error happened but this time it at least outputs a graph.

When I try running the example file,  another error happens. I attached a screenshot of the error. The error summarizes as "Not a binary Mat-file. Try load -ASCII to read as a text
![Screenshot 2023-06-10 053705](https://github.com/teasit/magic-formula-tyre-tool/assets/39840319/3173f3c1-cd49-42c7-af78-e5540f662701)
![Screenshot 2023-06-10 053546](https://github.com/teasit/magic-formula-tyre-tool/assets/39840319/6141d602-9a63-45ea-999c-b29a914a638b)
![Screenshot 2023-06-10 053506](https://github.com/teasit/magic-formula-tyre-tool/assets/39840319/76415d49-3c3c-492b-a090-820153e10a25)

**Comment by teasit** [comment] 2023-06-11 18:26
Hey, 

I cannot reproduce this, sorry. I tried with R2023a without getting error messages when loading the example data.
Make sure it is "RunData", not "RawData". If you can get to the point you posted pictures of, understand that certain runs in FSAE TTC only have data for certain steady-states. You can check the "Data" tab to see for which steady-states you have data to plot. If you load cornering data, you won't be able to plot the longitudinal force over slip ratio.

How did you install the app? Using the FileExchange or the toolbox installer?
Did you clone it yourself using Git? In case you cloned it, make sure you open the Project file before starting the app. It initializes all the required paths. This is done automatically if you used the app installer.

Hope that helps,
Tom

**Comment by CTchani** [comment] 2023-07-19 06:56
Hello Tom,

I'm having the same issue with Gianluca. However, after importing some data (Run 31 and 34 from Round 5 of testing, to be specific), every channel seemed to have no data when I tried to plot the data in Tyre Analysis. In addition, whenever I tried to fit the tire data using one of the listed fit modes in the Tire Data tab, I got a downsampling error, which I suspect is connected to the data not having data. Am I correct? Or is this an issue caused by missing data from the non-fittable section (I didn't enter data such as effective radius before fitting because I don't currently have the data, but I also noticed that if the fitter required the data, it would usually output a different error message)?

Thank you

Robert

**Comment by CTchani** [comment] 2023-07-22 06:40
Hello Tom,

Thank you for the response! Unfortunately, despite my attempts to increase the threshold, I am still having downsizing issues. Did it work for you at 1%? I checked the data, and the slip angles varied quite a bit even during steady-state. However, I feel like 20% should have covered the variation.

Let me know what you think, and Thank you once again for helping.

Robert

![image](https://github.com/teasit/magic-formula-tyre-tool/assets/115762092/e32dcdb9-d696-4efa-a493-af00132e1f68)

**Comment by Zaga272** [comment] 2023-09-10 04:29
Hey guys,

I have the same downsizing issue. Is there an update on how to fix it? I tried the things from above but unfortunately the fitter is still not working and the command window shows that x has to be nonempty. Any help but would be really appreciated :D

Thanks

**Comment by Lukee44** [comment] 2023-09-15 09:43
Hey guys,
I have problems with the parser, the one which is available ' FSAETTC_SI_ISO_Mat' is not working; this is the error "Undefined function findpeaks for input argument of type double". 
Even if I choose the ExampleParser there is this error: "Method 'parse' is not defined for class 'tydex.parser.ExampleParsers' or is removed form MATLAB's search path". How can I fix these problems?
Could you please send me a parser that works?
Thank you very much for helping

**Comment by teasit** [comment] 2023-10-02 11:54
@Lukee44 If you cannot use `findpeaks`, you don't have the signal processing toolbox installed and therefore your installation does not satisfy the requirements.

**Comment by teasit** [comment] 2023-10-08 21:04
@Gianluca2 So in [v1.5.0](https://github.com/teasit/magic-formula-tyre-tool/releases/tag/v1.5.0) the issue while plotting should be fixed.

@CTchani Sorry I still haven't solved this, but I improved the import-panel a bit. You can now press a button to land in the parser file to edit it. If you have found a solution in the meantime, please let me know.

**Closed by teasit** 2023-10-08 21:04 UTC
