### ISSUE TITLE
[BUG] Undefined function 'findpeaks' for input arguments of type 'double'

### ISSUE THREAD

**Issue by LuisGoesMR** [teasit/magic-formula-tyre-tool#2] opened 2022-09-28 01:25 UTC
**Description**
Hello, I'm a Student and member of a FSAE Team in Brazil, and I'm really thankful for the type of content you are developing and sharing with the student community! I'm really new to the Tire Modelling scenario and you helped me make a lot of concepts a lot more clear! 
Well, I tried to implement your software but right from the start I get stuck on an error message... When I try importing my data (even the example data that comes with the download of this tool), I get this message: "Undefined funcion 'findpeaks' for input arguments of type 'double'."

**Reproduce**
1. Go to 'Import Data'
2. Go to the location of the file
3. Select the Data from TTC 
4. Click 'Import'

**Expected behavior**
The expected behavior was being able to continue the step by step you described on the post...

**Screenshots**
Screenshot of the error message:
![image](https://user-images.githubusercontent.com/114544500/192665701-d821b3cf-861f-490d-be1b-b87563ab339d.png)

**Version of MATLAB**
 - MATLAB OS
 - 2022b 30day Trial version

Do you have any clue on how can I fix this issue? 
Once again, thanks for the help anyways!!

**Comment by teasit** [comment] 2022-09-28 07:53
Hello Luis,

Welcome to the world of tire modeling. 😀

The function `findpeaks` comes with the 'Signal Processing Toolbox'. This toolbox is listed as a requirement on the FileExchange page and the GitHub README. Please make sure you have installed both the 'Optimization Toolbox' and 'Signal Processing Toolbox'!

As for MATLAB 2022b, I am not sure it is compatible as it has been released very recently and not been tested yet. If you want to make sure everything works as intended, please install MATLAB R2021a with said toolboxes.

Greetings
Tom

**Comment by LuisGoesMR** [comment] 2022-09-28 13:12
Hello Tom!

Thanks for the help! As soon as I get to the University I'll try installing the Toolbox and I'll let you know if it works on MATLAB 20220b.

Greetings!
Luis

**Comment by teasit** [comment] 2022-10-02 15:56
Hey Luis,

I am assuming that your problem has been resolved by installing the required toolboxes.
If that is not the case, feel free to re-open this issue.

Greetings
Tom

**Closed by teasit** 2022-10-02 15:56 UTC
Labels: help wanted
